version: 2
updates:
  - package-ecosystem: docker
    allow:
      dependency-name: niis/harmony-ap
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
      timezone: Europe/Helsinki
    directory: /
