version: 2
updates:
  - package-ecosystem: docker
    allow:
      dependency-name: niis/harmony-ap
    schedule:
      interval: weekly
      day: sunday
    directory: /
    reviewers:
      - fintraffic-efti/developers

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - fintraffic-efti/developers
