services:
  harmony-h1:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      # ./start.sh generates env file
      - local/h1/.env
    environment:
      - DB_HOST=db-h1
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      # Simplify plugin password requirements for development setup
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      # Password for pmode plugin
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=h1
      - SERVER_FQDN=harmony-h1
      - SECURITY_KEYSTORE_PASSWORD=ap-keystore-h1
      - SECURITY_TRUSTSTORE_PASSWORD=ap-truststore-h1
      - TLS_KEYSTORE_PASSWORD=tls-keystore-h1
      - TLS_TRUSTSTORE_PASSWORD=tls-truststore-h1
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
    restart: always
    ports:
      - "127.0.0.1:10443:8443"
    depends_on:
      - db-h1

  db-h1:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    restart: on-failure
    ports:
      - "127.0.0.1:13306:3306"
    mem_limit: 512m

  harmony-h2:
    image: nginx
    depends_on:
      - harmony-h2-a
      - harmony-h2-b
    ports:
      - "10444:8081"
    volumes:
      - './local/h2/nginx.conf:/etc/nginx/nginx.conf'

  harmony-h2-a:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      # ./start.sh generates env file
      - local/h2/.env
    environment:
      - DB_HOST=db-h2
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      # Simplify plugin password requirements for development setup
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      # Password for pmode plugin
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=h2
      - SERVER_FQDN=harmony-h2
      - SECURITY_KEYSTORE_PASSWORD=ap-keystore-h2
      - SECURITY_TRUSTSTORE_PASSWORD=ap-truststore-h2
      - TLS_KEYSTORE_PASSWORD=tls-keystore-h2
      - TLS_TRUSTSTORE_PASSWORD=tls-truststore-h2
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
      - DEPLOYMENT_CLUSTERED=true
      - ACTIVEMQ_BROKER_HOST=harmony-jms-broker1,harmony-jms-broker2
      - ACTIVEMQ_BROKER_NAME=broker1,broker2
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      # Need EXTERNAL_LB in addition to DEPLOYMENT_CLUSTERED because of our init scripts
      - EXTERNAL_LB=true
    restart: always
    depends_on:
      - db-h2
      - harmony-jms-broker1
      - harmony-jms-broker2
    volumes:
      - harmony-h2-data:/var/opt/harmony-ap

  harmony-h2-b:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      # ./start.sh generates env file
      - local/h2/.env
    environment:
      - DB_HOST=db-h2
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      # Simplify plugin password requirements for development setup
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      # Password for pmode plugin
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=h2
      - SERVER_FQDN=harmony-h2
      - SECURITY_KEYSTORE_PASSWORD=ap-keystore-h2
      - SECURITY_TRUSTSTORE_PASSWORD=ap-truststore-h2
      - TLS_KEYSTORE_PASSWORD=tls-keystore-h2
      - TLS_TRUSTSTORE_PASSWORD=tls-truststore-h2
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
      - DEPLOYMENT_CLUSTERED=true
      - ACTIVEMQ_BROKER_HOST=harmony-jms-broker1,harmony-jms-broker2
      - ACTIVEMQ_BROKER_NAME=broker1,broker2
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      # Need EXTERNAL_LB in addition to DEPLOYMENT_CLUSTERED because of our init scripts
      - EXTERNAL_LB=true
    restart: always
    depends_on:
      - db-h2
      - harmony-jms-broker1
      - harmony-jms-broker2
    volumes:
      - harmony-h2-data:/var/opt/harmony-ap

  db-h2:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    restart: on-failure
    ports:
      - "127.0.0.1:13307:3306"
    mem_limit: 512m

  harmony-jms-broker1:
    image: apache/activemq-classic:5.18.3
    environment:
      - ACTIVEMQ_CONNECTION_USER=admin
      - ACTIVEMQ_CONNECTION_PASSWORD=admin
      - ACTIVEMQ_JMX_USER=admin
      - ACTIVEMQ_JMX_PASSWORD=admin
      - ACTIVEMQ_WEB_USER=webadmin
      - ACTIVEMQ_WEB_PASSWORD=admin
      - ACTIVEMQ_DATA=/var/opt/apache-activemq
      - ACTIVEMQ_TMP=/var/tmp
    mem_limit: 1000m
    volumes:
      - ./local/h2/activemq-broker1.xml:/opt/apache-activemq/conf/activemq-broker1.xml
      - harmony-jms-data:/var/opt/apache-activemq

  harmony-jms-broker2:
    image: apache/activemq-classic:5.18.3
    environment:
      - ACTIVEMQ_CONNECTION_USER=admin
      - ACTIVEMQ_CONNECTION_PASSWORD=admin
      - ACTIVEMQ_JMX_USER=admin
      - ACTIVEMQ_JMX_PASSWORD=admin
      - ACTIVEMQ_WEB_USER=webadmin
      - ACTIVEMQ_WEB_PASSWORD=admin
      - ACTIVEMQ_DATA=/var/opt/apache-activemq
      - ACTIVEMQ_TMP=/var/tmp
    mem_limit: 1000m
    volumes:
      - ./local/h2/activemq-broker2.xml:/opt/apache-activemq/conf/activemq-broker1.xml
      - harmony-jms-data:/var/opt/apache-activemq

volumes:
  harmony-h2-data:
  harmony-jms-data: