services:
  harmony:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      # Generate env file with: echo "EFTI_PMODE_BASE64=""$(cat dev/dev_pmode.xml | base64 --wrap 0)""" > .pmode.env
      - .pmode.env
    environment:
      - DB_HOST=db
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      # Simplify plugin password requirements for development setup
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      # Password for pmode plugin
      - PMODE_ADMIN_PASSWORD=efti_pmode
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=party_a
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
    restart: always
    ports:
      - "127.0.0.1:10443:8443"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    restart: on-failure
    ports:
      - "127.0.0.1:13306:3306"
    mem_limit: 512m
