name: Amazon ECR login
description: Configures AWS Credentials and log into Amazon ECR

inputs:
  role:
    description: AWS Role name
    required: true
  session-name:
    description: AWS Session name
    default: githubdeploymentsession
  region:
    description: AWS Region
    default: eu-west-1

outputs:
  registry:
    description: Amazon ECR Registry
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role }}
        role-session-name: ${{ inputs.session-name }}
        aws-region: ${{ inputs.region }}

    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr
